export const fontFamilies = [
  { label: "Arial", value: "Arial" },
  { label: "Times New Roman", value: "Times New Roman" },
  { label: "Courier New", value: "Courier New" },
  { label: "Verdana", value: "Verdana" },
  { label: "Helvetica", value: "Helvetica" },
  { label: "Georgia", value: "Georgia" },
  { label: "Palatino", value: "Palatino" },
  { label: "Garamond", value: "Garamond" },
  { label: "Comic Sans MS", value: "Comic Sans MS" },
  { label: "Impact", value: "Impact" },
  { label: "Trebuchet MS", value: "Trebuchet MS" },
  { label: "Courier", value: "Courier" },
  { label: "Lucida Console", value: "Lucida Console" },
  { label: "Tahoma", value: "Tahoma" },
  { label: "Geneva", value: "Geneva" },
  { label: "Optima", value: "Optima" },
  { label: "Gill Sans", value: "Gill Sans" },
  { label: "Futura", value: "Futura" },
  { label: "Baskerville", value: "Baskerville" },
  { label: "Calibri", value: "Calibri" },
  { label: "Rockwell", value: "Rockwell" },
  { label: "Arial Black", value: "Arial Black" },
  { label: "Brush Script MT", value: "Brush Script MT" },
  { label: "PT Serif", value: "PT Serif" },
];
